#ifndef BTS_MICROARCH_EVENTS_GENERATED_H
#define BTS_MICROARCH_EVENTS_GENERATED_H

/* Generated on the experiment host. */

#define BTS_EVT_L1D_REPLACEMENTS_AVAILABLE 1
#define BTS_EVT_L1D_REPLACEMENTS_TYPE 4u
#define BTS_EVT_L1D_REPLACEMENTS_CONFIG UINT64_C(0x151)
#define BTS_EVT_L1D_REPLACEMENTS_CONFIG1 UINT64_C(0x0)
#define BTS_EVT_L1D_REPLACEMENTS_CONFIG2 UINT64_C(0x0)
#define BTS_EVT_L1D_REPLACEMENTS_PRECISE_IP 0u

#define BTS_EVT_L2_REQUEST_MISSES_AVAILABLE 1
#define BTS_EVT_L2_REQUEST_MISSES_TYPE 4u
#define BTS_EVT_L2_REQUEST_MISSES_CONFIG UINT64_C(0x3f24)
#define BTS_EVT_L2_REQUEST_MISSES_CONFIG1 UINT64_C(0x0)
#define BTS_EVT_L2_REQUEST_MISSES_CONFIG2 UINT64_C(0x0)
#define BTS_EVT_L2_REQUEST_MISSES_PRECISE_IP 0u

#define BTS_EVT_LONG_LATENCY_LOADS_AVAILABLE 1
#define BTS_EVT_LONG_LATENCY_LOADS_TYPE 4u
#define BTS_EVT_LONG_LATENCY_LOADS_CONFIG UINT64_C(0x1cd)
#define BTS_EVT_LONG_LATENCY_LOADS_CONFIG1 UINT64_C(0x20)
#define BTS_EVT_LONG_LATENCY_LOADS_CONFIG2 UINT64_C(0x0)
#define BTS_EVT_LONG_LATENCY_LOADS_PRECISE_IP 2u

#define BTS_EVT_LOAD_L1_HIT_AVAILABLE 1
#define BTS_EVT_LOAD_L1_HIT_TYPE 4u
#define BTS_EVT_LOAD_L1_HIT_CONFIG UINT64_C(0x1d1)
#define BTS_EVT_LOAD_L1_HIT_CONFIG1 UINT64_C(0x0)
#define BTS_EVT_LOAD_L1_HIT_CONFIG2 UINT64_C(0x0)
#define BTS_EVT_LOAD_L1_HIT_PRECISE_IP 2u

#define BTS_EVT_LOAD_L2_HIT_AVAILABLE 1
#define BTS_EVT_LOAD_L2_HIT_TYPE 4u
#define BTS_EVT_LOAD_L2_HIT_CONFIG UINT64_C(0x2d1)
#define BTS_EVT_LOAD_L2_HIT_CONFIG1 UINT64_C(0x0)
#define BTS_EVT_LOAD_L2_HIT_CONFIG2 UINT64_C(0x0)
#define BTS_EVT_LOAD_L2_HIT_PRECISE_IP 2u

#define BTS_EVT_LOAD_L3_HIT_AVAILABLE 1
#define BTS_EVT_LOAD_L3_HIT_TYPE 4u
#define BTS_EVT_LOAD_L3_HIT_CONFIG UINT64_C(0x4d1)
#define BTS_EVT_LOAD_L3_HIT_CONFIG1 UINT64_C(0x0)
#define BTS_EVT_LOAD_L3_HIT_CONFIG2 UINT64_C(0x0)
#define BTS_EVT_LOAD_L3_HIT_PRECISE_IP 2u

#define BTS_EVT_LOAD_L1_MISS_AVAILABLE 1
#define BTS_EVT_LOAD_L1_MISS_TYPE 4u
#define BTS_EVT_LOAD_L1_MISS_CONFIG UINT64_C(0x8d1)
#define BTS_EVT_LOAD_L1_MISS_CONFIG1 UINT64_C(0x0)
#define BTS_EVT_LOAD_L1_MISS_CONFIG2 UINT64_C(0x0)
#define BTS_EVT_LOAD_L1_MISS_PRECISE_IP 2u

#define BTS_EVT_LOAD_L2_MISS_AVAILABLE 1
#define BTS_EVT_LOAD_L2_MISS_TYPE 4u
#define BTS_EVT_LOAD_L2_MISS_CONFIG UINT64_C(0x10d1)
#define BTS_EVT_LOAD_L2_MISS_CONFIG1 UINT64_C(0x0)
#define BTS_EVT_LOAD_L2_MISS_CONFIG2 UINT64_C(0x0)
#define BTS_EVT_LOAD_L2_MISS_PRECISE_IP 2u

#define BTS_EVT_LOAD_L3_MISS_AVAILABLE 1
#define BTS_EVT_LOAD_L3_MISS_TYPE 4u
#define BTS_EVT_LOAD_L3_MISS_CONFIG UINT64_C(0x20d1)
#define BTS_EVT_LOAD_L3_MISS_CONFIG1 UINT64_C(0x0)
#define BTS_EVT_LOAD_L3_MISS_CONFIG2 UINT64_C(0x0)
#define BTS_EVT_LOAD_L3_MISS_PRECISE_IP 2u

#define BTS_EVT_STALLS_L1D_MISS_AVAILABLE 1
#define BTS_EVT_STALLS_L1D_MISS_TYPE 4u
#define BTS_EVT_STALLS_L1D_MISS_CONFIG UINT64_C(0xc000ca3)
#define BTS_EVT_STALLS_L1D_MISS_CONFIG1 UINT64_C(0x0)
#define BTS_EVT_STALLS_L1D_MISS_CONFIG2 UINT64_C(0x0)
#define BTS_EVT_STALLS_L1D_MISS_PRECISE_IP 0u

#define BTS_EVT_STALLS_MEM_ANY_AVAILABLE 1
#define BTS_EVT_STALLS_MEM_ANY_TYPE 4u
#define BTS_EVT_STALLS_MEM_ANY_CONFIG UINT64_C(0x40004a3)
#define BTS_EVT_STALLS_MEM_ANY_CONFIG1 UINT64_C(0x0)
#define BTS_EVT_STALLS_MEM_ANY_CONFIG2 UINT64_C(0x0)
#define BTS_EVT_STALLS_MEM_ANY_PRECISE_IP 0u

#define BTS_EVT_MACHINE_CLEARS_AVAILABLE 1
#define BTS_EVT_MACHINE_CLEARS_TYPE 4u
#define BTS_EVT_MACHINE_CLEARS_CONFIG UINT64_C(0x10401c3)
#define BTS_EVT_MACHINE_CLEARS_CONFIG1 UINT64_C(0x0)
#define BTS_EVT_MACHINE_CLEARS_CONFIG2 UINT64_C(0x0)
#define BTS_EVT_MACHINE_CLEARS_PRECISE_IP 0u

#define BTS_EVT_MEMORY_ORDERING_CLEARS_AVAILABLE 1
#define BTS_EVT_MEMORY_ORDERING_CLEARS_TYPE 4u
#define BTS_EVT_MEMORY_ORDERING_CLEARS_CONFIG UINT64_C(0x2c3)
#define BTS_EVT_MEMORY_ORDERING_CLEARS_CONFIG1 UINT64_C(0x0)
#define BTS_EVT_MEMORY_ORDERING_CLEARS_CONFIG2 UINT64_C(0x0)
#define BTS_EVT_MEMORY_ORDERING_CLEARS_PRECISE_IP 0u

#define BTS_EVT_RECOVERY_CYCLES_AVAILABLE 1
#define BTS_EVT_RECOVERY_CYCLES_TYPE 4u
#define BTS_EVT_RECOVERY_CYCLES_CONFIG UINT64_C(0x1ad)
#define BTS_EVT_RECOVERY_CYCLES_CONFIG1 UINT64_C(0x0)
#define BTS_EVT_RECOVERY_CYCLES_CONFIG2 UINT64_C(0x0)
#define BTS_EVT_RECOVERY_CYCLES_PRECISE_IP 0u

#define BTS_EVT_RECOVERY_CYCLES_ANY_AVAILABLE 1
#define BTS_EVT_RECOVERY_CYCLES_ANY_TYPE 4u
#define BTS_EVT_RECOVERY_CYCLES_ANY_CONFIG UINT64_C(0x1ad)
#define BTS_EVT_RECOVERY_CYCLES_ANY_CONFIG1 UINT64_C(0x0)
#define BTS_EVT_RECOVERY_CYCLES_ANY_CONFIG2 UINT64_C(0x0)
#define BTS_EVT_RECOVERY_CYCLES_ANY_PRECISE_IP 0u

#define BTS_EVT_UOPS_RETIRED_SLOTS_AVAILABLE 1
#define BTS_EVT_UOPS_RETIRED_SLOTS_TYPE 4u
#define BTS_EVT_UOPS_RETIRED_SLOTS_CONFIG UINT64_C(0x2c2)
#define BTS_EVT_UOPS_RETIRED_SLOTS_CONFIG1 UINT64_C(0x0)
#define BTS_EVT_UOPS_RETIRED_SLOTS_CONFIG2 UINT64_C(0x0)
#define BTS_EVT_UOPS_RETIRED_SLOTS_PRECISE_IP 0u

#define BTS_EVT_UOPS_ISSUED_ANY_AVAILABLE 1
#define BTS_EVT_UOPS_ISSUED_ANY_TYPE 4u
#define BTS_EVT_UOPS_ISSUED_ANY_CONFIG UINT64_C(0x1ae)
#define BTS_EVT_UOPS_ISSUED_ANY_CONFIG1 UINT64_C(0x0)
#define BTS_EVT_UOPS_ISSUED_ANY_CONFIG2 UINT64_C(0x0)
#define BTS_EVT_UOPS_ISSUED_ANY_PRECISE_IP 0u

#define BTS_EVT_UOPS_EXECUTED_THREAD_AVAILABLE 1
#define BTS_EVT_UOPS_EXECUTED_THREAD_TYPE 4u
#define BTS_EVT_UOPS_EXECUTED_THREAD_CONFIG UINT64_C(0x1b1)
#define BTS_EVT_UOPS_EXECUTED_THREAD_CONFIG1 UINT64_C(0x0)
#define BTS_EVT_UOPS_EXECUTED_THREAD_CONFIG2 UINT64_C(0x0)
#define BTS_EVT_UOPS_EXECUTED_THREAD_PRECISE_IP 0u

#define BTS_EVT_IDQ_UOPS_NOT_DELIVERED_AVAILABLE 1
#define BTS_EVT_IDQ_UOPS_NOT_DELIVERED_TYPE 4u
#define BTS_EVT_IDQ_UOPS_NOT_DELIVERED_CONFIG UINT64_C(0x19c)
#define BTS_EVT_IDQ_UOPS_NOT_DELIVERED_CONFIG1 UINT64_C(0x0)
#define BTS_EVT_IDQ_UOPS_NOT_DELIVERED_CONFIG2 UINT64_C(0x0)
#define BTS_EVT_IDQ_UOPS_NOT_DELIVERED_PRECISE_IP 0u

#define BTS_EVT_IDQ_MITE_UOPS_AVAILABLE 1
#define BTS_EVT_IDQ_MITE_UOPS_TYPE 4u
#define BTS_EVT_IDQ_MITE_UOPS_CONFIG UINT64_C(0x479)
#define BTS_EVT_IDQ_MITE_UOPS_CONFIG1 UINT64_C(0x0)
#define BTS_EVT_IDQ_MITE_UOPS_CONFIG2 UINT64_C(0x0)
#define BTS_EVT_IDQ_MITE_UOPS_PRECISE_IP 0u

#define BTS_EVT_IDQ_DSB_UOPS_AVAILABLE 1
#define BTS_EVT_IDQ_DSB_UOPS_TYPE 4u
#define BTS_EVT_IDQ_DSB_UOPS_CONFIG UINT64_C(0x879)
#define BTS_EVT_IDQ_DSB_UOPS_CONFIG1 UINT64_C(0x0)
#define BTS_EVT_IDQ_DSB_UOPS_CONFIG2 UINT64_C(0x0)
#define BTS_EVT_IDQ_DSB_UOPS_PRECISE_IP 0u

#define BTS_EVT_IDQ_MS_UOPS_AVAILABLE 1
#define BTS_EVT_IDQ_MS_UOPS_TYPE 4u
#define BTS_EVT_IDQ_MS_UOPS_CONFIG UINT64_C(0x2079)
#define BTS_EVT_IDQ_MS_UOPS_CONFIG1 UINT64_C(0x0)
#define BTS_EVT_IDQ_MS_UOPS_CONFIG2 UINT64_C(0x0)
#define BTS_EVT_IDQ_MS_UOPS_PRECISE_IP 0u

#define BTS_EVT_BR_CONDITIONAL_AVAILABLE 1
#define BTS_EVT_BR_CONDITIONAL_TYPE 4u
#define BTS_EVT_BR_CONDITIONAL_CONFIG UINT64_C(0x11c4)
#define BTS_EVT_BR_CONDITIONAL_CONFIG1 UINT64_C(0x0)
#define BTS_EVT_BR_CONDITIONAL_CONFIG2 UINT64_C(0x0)
#define BTS_EVT_BR_CONDITIONAL_PRECISE_IP 0u

#define BTS_EVT_BR_CONDITIONAL_TAKEN_AVAILABLE 1
#define BTS_EVT_BR_CONDITIONAL_TAKEN_TYPE 4u
#define BTS_EVT_BR_CONDITIONAL_TAKEN_CONFIG UINT64_C(0x1c4)
#define BTS_EVT_BR_CONDITIONAL_TAKEN_CONFIG1 UINT64_C(0x0)
#define BTS_EVT_BR_CONDITIONAL_TAKEN_CONFIG2 UINT64_C(0x0)
#define BTS_EVT_BR_CONDITIONAL_TAKEN_PRECISE_IP 0u

#define BTS_EVT_BR_CONDITIONAL_NOT_TAKEN_AVAILABLE 1
#define BTS_EVT_BR_CONDITIONAL_NOT_TAKEN_TYPE 4u
#define BTS_EVT_BR_CONDITIONAL_NOT_TAKEN_CONFIG UINT64_C(0x10c4)
#define BTS_EVT_BR_CONDITIONAL_NOT_TAKEN_CONFIG1 UINT64_C(0x0)
#define BTS_EVT_BR_CONDITIONAL_NOT_TAKEN_CONFIG2 UINT64_C(0x0)
#define BTS_EVT_BR_CONDITIONAL_NOT_TAKEN_PRECISE_IP 0u

#define BTS_EVT_BR_MISPRED_CONDITIONAL_AVAILABLE 1
#define BTS_EVT_BR_MISPRED_CONDITIONAL_TYPE 4u
#define BTS_EVT_BR_MISPRED_CONDITIONAL_CONFIG UINT64_C(0x11c5)
#define BTS_EVT_BR_MISPRED_CONDITIONAL_CONFIG1 UINT64_C(0x0)
#define BTS_EVT_BR_MISPRED_CONDITIONAL_CONFIG2 UINT64_C(0x0)
#define BTS_EVT_BR_MISPRED_CONDITIONAL_PRECISE_IP 0u

#define BTS_EVT_RESOURCE_STALLS_SCOREBOARD_AVAILABLE 1
#define BTS_EVT_RESOURCE_STALLS_SCOREBOARD_TYPE 4u
#define BTS_EVT_RESOURCE_STALLS_SCOREBOARD_CONFIG UINT64_C(0x2a2)
#define BTS_EVT_RESOURCE_STALLS_SCOREBOARD_CONFIG1 UINT64_C(0x0)
#define BTS_EVT_RESOURCE_STALLS_SCOREBOARD_CONFIG2 UINT64_C(0x0)
#define BTS_EVT_RESOURCE_STALLS_SCOREBOARD_PRECISE_IP 0u

#define BTS_EVT_RESOURCE_STALLS_STORE_BUFFER_AVAILABLE 1
#define BTS_EVT_RESOURCE_STALLS_STORE_BUFFER_TYPE 4u
#define BTS_EVT_RESOURCE_STALLS_STORE_BUFFER_CONFIG UINT64_C(0x8a2)
#define BTS_EVT_RESOURCE_STALLS_STORE_BUFFER_CONFIG1 UINT64_C(0x0)
#define BTS_EVT_RESOURCE_STALLS_STORE_BUFFER_CONFIG2 UINT64_C(0x0)
#define BTS_EVT_RESOURCE_STALLS_STORE_BUFFER_PRECISE_IP 0u

#define BTS_EVT_EXECUTION_BOUND_LOADS_AVAILABLE 1
#define BTS_EVT_EXECUTION_BOUND_LOADS_TYPE 4u
#define BTS_EVT_EXECUTION_BOUND_LOADS_CONFIG UINT64_C(0x50021a6)
#define BTS_EVT_EXECUTION_BOUND_LOADS_CONFIG1 UINT64_C(0x0)
#define BTS_EVT_EXECUTION_BOUND_LOADS_CONFIG2 UINT64_C(0x0)
#define BTS_EVT_EXECUTION_BOUND_LOADS_PRECISE_IP 0u

#endif
