#ifndef CYF_MICROARCH_EVENTS_GENERATED_H
#define CYF_MICROARCH_EVENTS_GENERATED_H

/* Generated on the experiment host. */

#define CYF_EVT_L1D_REPLACEMENTS_AVAILABLE 1
#define CYF_EVT_L1D_REPLACEMENTS_TYPE 4u
#define CYF_EVT_L1D_REPLACEMENTS_CONFIG UINT64_C(0x151)
#define CYF_EVT_L1D_REPLACEMENTS_CONFIG1 UINT64_C(0x0)
#define CYF_EVT_L1D_REPLACEMENTS_CONFIG2 UINT64_C(0x0)
#define CYF_EVT_L1D_REPLACEMENTS_PRECISE_IP 0u

#define CYF_EVT_L2_REQUEST_MISSES_AVAILABLE 1
#define CYF_EVT_L2_REQUEST_MISSES_TYPE 4u
#define CYF_EVT_L2_REQUEST_MISSES_CONFIG UINT64_C(0x3f24)
#define CYF_EVT_L2_REQUEST_MISSES_CONFIG1 UINT64_C(0x0)
#define CYF_EVT_L2_REQUEST_MISSES_CONFIG2 UINT64_C(0x0)
#define CYF_EVT_L2_REQUEST_MISSES_PRECISE_IP 0u

#define CYF_EVT_LONG_LATENCY_LOADS_AVAILABLE 1
#define CYF_EVT_LONG_LATENCY_LOADS_TYPE 4u
#define CYF_EVT_LONG_LATENCY_LOADS_CONFIG UINT64_C(0x1cd)
#define CYF_EVT_LONG_LATENCY_LOADS_CONFIG1 UINT64_C(0x20)
#define CYF_EVT_LONG_LATENCY_LOADS_CONFIG2 UINT64_C(0x0)
#define CYF_EVT_LONG_LATENCY_LOADS_PRECISE_IP 2u

#define CYF_EVT_LOAD_L1_HIT_AVAILABLE 1
#define CYF_EVT_LOAD_L1_HIT_TYPE 4u
#define CYF_EVT_LOAD_L1_HIT_CONFIG UINT64_C(0x1d1)
#define CYF_EVT_LOAD_L1_HIT_CONFIG1 UINT64_C(0x0)
#define CYF_EVT_LOAD_L1_HIT_CONFIG2 UINT64_C(0x0)
#define CYF_EVT_LOAD_L1_HIT_PRECISE_IP 2u

#define CYF_EVT_LOAD_L2_HIT_AVAILABLE 1
#define CYF_EVT_LOAD_L2_HIT_TYPE 4u
#define CYF_EVT_LOAD_L2_HIT_CONFIG UINT64_C(0x2d1)
#define CYF_EVT_LOAD_L2_HIT_CONFIG1 UINT64_C(0x0)
#define CYF_EVT_LOAD_L2_HIT_CONFIG2 UINT64_C(0x0)
#define CYF_EVT_LOAD_L2_HIT_PRECISE_IP 2u

#define CYF_EVT_LOAD_L3_HIT_AVAILABLE 1
#define CYF_EVT_LOAD_L3_HIT_TYPE 4u
#define CYF_EVT_LOAD_L3_HIT_CONFIG UINT64_C(0x4d1)
#define CYF_EVT_LOAD_L3_HIT_CONFIG1 UINT64_C(0x0)
#define CYF_EVT_LOAD_L3_HIT_CONFIG2 UINT64_C(0x0)
#define CYF_EVT_LOAD_L3_HIT_PRECISE_IP 2u

#define CYF_EVT_LOAD_L1_MISS_AVAILABLE 1
#define CYF_EVT_LOAD_L1_MISS_TYPE 4u
#define CYF_EVT_LOAD_L1_MISS_CONFIG UINT64_C(0x8d1)
#define CYF_EVT_LOAD_L1_MISS_CONFIG1 UINT64_C(0x0)
#define CYF_EVT_LOAD_L1_MISS_CONFIG2 UINT64_C(0x0)
#define CYF_EVT_LOAD_L1_MISS_PRECISE_IP 2u

#define CYF_EVT_LOAD_L2_MISS_AVAILABLE 1
#define CYF_EVT_LOAD_L2_MISS_TYPE 4u
#define CYF_EVT_LOAD_L2_MISS_CONFIG UINT64_C(0x10d1)
#define CYF_EVT_LOAD_L2_MISS_CONFIG1 UINT64_C(0x0)
#define CYF_EVT_LOAD_L2_MISS_CONFIG2 UINT64_C(0x0)
#define CYF_EVT_LOAD_L2_MISS_PRECISE_IP 2u

#define CYF_EVT_LOAD_L3_MISS_AVAILABLE 1
#define CYF_EVT_LOAD_L3_MISS_TYPE 4u
#define CYF_EVT_LOAD_L3_MISS_CONFIG UINT64_C(0x20d1)
#define CYF_EVT_LOAD_L3_MISS_CONFIG1 UINT64_C(0x0)
#define CYF_EVT_LOAD_L3_MISS_CONFIG2 UINT64_C(0x0)
#define CYF_EVT_LOAD_L3_MISS_PRECISE_IP 2u

#define CYF_EVT_STALLS_L1D_MISS_AVAILABLE 1
#define CYF_EVT_STALLS_L1D_MISS_TYPE 4u
#define CYF_EVT_STALLS_L1D_MISS_CONFIG UINT64_C(0xc000ca3)
#define CYF_EVT_STALLS_L1D_MISS_CONFIG1 UINT64_C(0x0)
#define CYF_EVT_STALLS_L1D_MISS_CONFIG2 UINT64_C(0x0)
#define CYF_EVT_STALLS_L1D_MISS_PRECISE_IP 0u

#define CYF_EVT_STALLS_MEM_ANY_AVAILABLE 1
#define CYF_EVT_STALLS_MEM_ANY_TYPE 4u
#define CYF_EVT_STALLS_MEM_ANY_CONFIG UINT64_C(0x40004a3)
#define CYF_EVT_STALLS_MEM_ANY_CONFIG1 UINT64_C(0x0)
#define CYF_EVT_STALLS_MEM_ANY_CONFIG2 UINT64_C(0x0)
#define CYF_EVT_STALLS_MEM_ANY_PRECISE_IP 0u

#define CYF_EVT_MACHINE_CLEARS_AVAILABLE 1
#define CYF_EVT_MACHINE_CLEARS_TYPE 4u
#define CYF_EVT_MACHINE_CLEARS_CONFIG UINT64_C(0x10401c3)
#define CYF_EVT_MACHINE_CLEARS_CONFIG1 UINT64_C(0x0)
#define CYF_EVT_MACHINE_CLEARS_CONFIG2 UINT64_C(0x0)
#define CYF_EVT_MACHINE_CLEARS_PRECISE_IP 0u

#define CYF_EVT_MEMORY_ORDERING_CLEARS_AVAILABLE 1
#define CYF_EVT_MEMORY_ORDERING_CLEARS_TYPE 4u
#define CYF_EVT_MEMORY_ORDERING_CLEARS_CONFIG UINT64_C(0x2c3)
#define CYF_EVT_MEMORY_ORDERING_CLEARS_CONFIG1 UINT64_C(0x0)
#define CYF_EVT_MEMORY_ORDERING_CLEARS_CONFIG2 UINT64_C(0x0)
#define CYF_EVT_MEMORY_ORDERING_CLEARS_PRECISE_IP 0u

#define CYF_EVT_RECOVERY_CYCLES_AVAILABLE 1
#define CYF_EVT_RECOVERY_CYCLES_TYPE 4u
#define CYF_EVT_RECOVERY_CYCLES_CONFIG UINT64_C(0x1ad)
#define CYF_EVT_RECOVERY_CYCLES_CONFIG1 UINT64_C(0x0)
#define CYF_EVT_RECOVERY_CYCLES_CONFIG2 UINT64_C(0x0)
#define CYF_EVT_RECOVERY_CYCLES_PRECISE_IP 0u

#define CYF_EVT_RECOVERY_CYCLES_ANY_AVAILABLE 0
#define CYF_EVT_RECOVERY_CYCLES_ANY_TYPE 0u
#define CYF_EVT_RECOVERY_CYCLES_ANY_CONFIG UINT64_C(0x0)
#define CYF_EVT_RECOVERY_CYCLES_ANY_CONFIG1 UINT64_C(0x0)
#define CYF_EVT_RECOVERY_CYCLES_ANY_CONFIG2 UINT64_C(0x0)
#define CYF_EVT_RECOVERY_CYCLES_ANY_PRECISE_IP 0u

#endif
