#!/usr/bin/env bash

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd -- "$SCRIPT_DIR/../.." && pwd)"

CYF_RESULTS_DIR="${CYF_RESULTS_DIR:-$REPO_ROOT/results/Carry_Your_Fault/two_window}"
CYF_BIN_DIR="${CYF_BIN_DIR:-$REPO_ROOT/build/bin/carry_your_fault}"

CYF_PROFILE_A_SAMPLES="${CYF_PROFILE_A_SAMPLES:-2000}"
CYF_PROFILE_B_SAMPLES="${CYF_PROFILE_B_SAMPLES:-2000}"
CYF_THRESHOLD_SAMPLES="${CYF_THRESHOLD_SAMPLES:-5000}"
CYF_CALIBRATION_SAMPLES="${CYF_CALIBRATION_SAMPLES:-5000}"
CYF_VALIDATION_SAMPLES="${CYF_VALIDATION_SAMPLES:-10000}"
CYF_ATTACK_DEVELOPMENT_SAMPLES="${CYF_ATTACK_DEVELOPMENT_SAMPLES:-1000}"
CYF_ATTACK_TEST_SAMPLES="${CYF_ATTACK_TEST_SAMPLES:-1000}"

CYF_DATA_DOMAIN="${CYF_DATA_DOMAIN:-0x43594631}"
CYF_BLOCK_SAMPLES="${CYF_BLOCK_SAMPLES:-100}"
CYF_WARMUP="${CYF_WARMUP:-100}"
CYF_CPU="${CYF_CPU:-0}"
CYF_TARGET_COEFF="${CYF_TARGET_COEFF:-17}"
CYF_MIN_RUNNING="${CYF_MIN_RUNNING:-95.0}"

CYF_TARGET_FPR="${CYF_TARGET_FPR:-0.10}"
CYF_TOP_K="${CYF_TOP_K:-8}"
CYF_MINIMUM_EFFECT="${CYF_MINIMUM_EFFECT:-0.15}"
CYF_MINIMUM_SCALE="${CYF_MINIMUM_SCALE:-1.0}"
CYF_MAX_BASELINE_DRIFT="${CYF_MAX_BASELINE_DRIFT:-0.50}"
CYF_MAX_ZERO_RATE_DRIFT="${CYF_MAX_ZERO_RATE_DRIFT:-0.05}"
CYF_MAX_KS_DISTANCE="${CYF_MAX_KS_DISTANCE:-0.10}"
CYF_MIN_IQR_RATIO="${CYF_MIN_IQR_RATIO:-0.50}"
CYF_MAX_IQR_RATIO="${CYF_MAX_IQR_RATIO:-2.00}"
CYF_MAX_QUANTILE_DRIFT="${CYF_MAX_QUANTILE_DRIFT:-1.00}"
CYF_DRIFT_MULTIPLIER="${CYF_DRIFT_MULTIPLIER:-3.0}"
CYF_MIN_BLOCK_DIRECTION_CONSISTENCY="${CYF_MIN_BLOCK_DIRECTION_CONSISTENCY:-0.80}"
CYF_MAX_BLOCK_CONTRIBUTION="${CYF_MAX_BLOCK_CONTRIBUTION:-0.50}"
CYF_BOOTSTRAP_ITERATIONS="${CYF_BOOTSTRAP_ITERATIONS:-2000}"
CYF_BOOTSTRAP_SEED="${CYF_BOOTSTRAP_SEED:-12648430}"
CYF_CV_FOLDS="${CYF_CV_FOLDS:-5}"
CYF_MIN_CV_MEDIAN_AUC="${CYF_MIN_CV_MEDIAN_AUC:-0.60}"
CYF_MIN_CV_FOLD_AUC="${CYF_MIN_CV_FOLD_AUC:-0.52}"
CYF_MIN_SELECTED_FEATURES="${CYF_MIN_SELECTED_FEATURES:-3}"
CYF_MAX_FEATURE_WEIGHT="${CYF_MAX_FEATURE_WEIGHT:-0.50}"
CYF_CORRELATION_THRESHOLD="${CYF_CORRELATION_THRESHOLD:-0.95}"
CYF_WEIGHT_POWER="${CYF_WEIGHT_POWER:-1.0}"
CYF_CLIP_Z="${CYF_CLIP_Z:-20.0}"

CYF_CALIBRATION_ALARM_TOLERANCE="${CYF_CALIBRATION_ALARM_TOLERANCE:-0.02}"
CYF_CALIBRATION_ALARM_RATIO="${CYF_CALIBRATION_ALARM_RATIO:-0.50}"
CYF_MAX_SCORE_MEDIAN_DRIFT="${CYF_MAX_SCORE_MEDIAN_DRIFT:-1.0}"
CYF_MAX_CALIBRATION_FEATURE_DRIFT="${CYF_MAX_CALIBRATION_FEATURE_DRIFT:-1.0}"
CYF_MIN_TEST_AUC="${CYF_MIN_TEST_AUC:-0.50}"
CYF_REQUIRE_TPR_GREATER_THAN_FPR="${CYF_REQUIRE_TPR_GREATER_THAN_FPR:-1}"
CYF_REQUIRE_POSITIVE_BOOTSTRAP_GAP="${CYF_REQUIRE_POSITIVE_BOOTSTRAP_GAP:-1}"

CYF_PASSES="${CYF_PASSES:-structural cache cache-detail load-hits load-misses-latency stalls recovery}"
CYF_WINDOWS="${CYF_WINDOWS:-exact-a2b post-fault}"

# Batch-level cache-reference analysis.  A point is reportable only when every
# required dataset contains at least CYF_BATCH_MIN_BATCHES non-overlapping
# batches.  Increase sample counts for batch size 5000, e.g. to >=25000.
CYF_BATCH_SIZES="${CYF_BATCH_SIZES:-100 500 1000 5000}"
CYF_BATCH_MIN_BATCHES="${CYF_BATCH_MIN_BATCHES:-5}"
CYF_BATCH_TARGET_FPR="${CYF_BATCH_TARGET_FPR:-0.10}"
CYF_BATCH_CALIBRATION_TOLERANCE="${CYF_BATCH_CALIBRATION_TOLERANCE:-0.10}"
CYF_STRICT_ANALYZER="${CYF_STRICT_ANALYZER:-0}"

# Reproducible randomized collection schedule.  Pair order codes written to CSV:
# 1 = AB (baseline first), 2 = BA (attack first).
CYF_EXPERIMENT_RUN="${CYF_EXPERIMENT_RUN:-0}"
CYF_SCHEDULE_SEED="${CYF_SCHEDULE_SEED:-20260715}"

# Confidence intervals and pair-order audit for batch analysis.
CYF_BATCH_BOOTSTRAP_ITERATIONS="${CYF_BATCH_BOOTSTRAP_ITERATIONS:-2000}"
CYF_BATCH_BOOTSTRAP_SEED="${CYF_BATCH_BOOTSTRAP_SEED:-12648430}"
CYF_BATCH_MIN_ORDER_BLOCKS="${CYF_BATCH_MIN_ORDER_BLOCKS:-3}"
CYF_BATCH_REQUIRE_ORDER_STRATA="${CYF_BATCH_REQUIRE_ORDER_STRATA:-0}"

# Dedicated independent-replication experiment.  This mode measures only the
# cache-detail pass, because cache_references is the predeclared batch feature.
# Each run has independent development/threshold/calibration/validation/test
# data, a distinct data domain, and a distinct randomized AB/BA schedule.
CYF_REPLICATE_RESULTS_DIR="${CYF_REPLICATE_RESULTS_DIR:-$REPO_ROOT/results/Carry_Your_Fault/replicated_batch}"
CYF_REPLICATE_RUNS="${CYF_REPLICATE_RUNS:-5}"
CYF_REPLICATE_BASE_SEED="${CYF_REPLICATE_BASE_SEED:-2026071501}"
CYF_REPLICATE_SEED_STEP="${CYF_REPLICATE_SEED_STEP:-104729}"
CYF_REPLICATE_RESET="${CYF_REPLICATE_RESET:-1}"
CYF_REPLICATE_SLEEP_SECONDS="${CYF_REPLICATE_SLEEP_SECONDS:-0}"
CYF_REP_BLOCK_SAMPLES="${CYF_REP_BLOCK_SAMPLES:-100}"
CYF_REP_THRESHOLD_SAMPLES="${CYF_REP_THRESHOLD_SAMPLES:-10000}"
CYF_REP_CALIBRATION_SAMPLES="${CYF_REP_CALIBRATION_SAMPLES:-10000}"
CYF_REP_VALIDATION_SAMPLES="${CYF_REP_VALIDATION_SAMPLES:-30000}"
CYF_REP_DEVELOPMENT_SAMPLES="${CYF_REP_DEVELOPMENT_SAMPLES:-10000}"
CYF_REP_TEST_SAMPLES="${CYF_REP_TEST_SAMPLES:-10000}"
CYF_REP_BATCH_SIZES="${CYF_REP_BATCH_SIZES:-100 500 1000}"
CYF_REP_MIN_BATCHES="${CYF_REP_MIN_BATCHES:-10}"
CYF_REP_MIN_ORDER_BLOCKS="${CYF_REP_MIN_ORDER_BLOCKS:-10}"
CYF_REP_WARMUP="${CYF_REP_WARMUP:-100}"

# Cross-run replication criteria.
CYF_REP_MIN_REPORTABLE_RUNS="${CYF_REP_MIN_REPORTABLE_RUNS:-3}"
CYF_REP_MIN_DIRECTION_CONSISTENCY="${CYF_REP_MIN_DIRECTION_CONSISTENCY:-0.80}"
CYF_REP_MIN_MEDIAN_AUC="${CYF_REP_MIN_MEDIAN_AUC:-0.80}"
CYF_REP_MIN_RUN_AUC="${CYF_REP_MIN_RUN_AUC:-0.60}"
CYF_REP_SUMMARY_BOOTSTRAP_ITERATIONS="${CYF_REP_SUMMARY_BOOTSTRAP_ITERATIONS:-5000}"
CYF_REP_SUMMARY_BOOTSTRAP_SEED="${CYF_REP_SUMMARY_BOOTSTRAP_SEED:-195936478}"
CYF_REP_TARGET_FPR="${CYF_REP_TARGET_FPR:-0.01}"
CYF_REP_CALIBRATION_TOLERANCE="${CYF_REP_CALIBRATION_TOLERANCE:-0.02}"
