KRAHMER_PQCLEAN_ROOT := $(REPO_ROOT)/third_party/pqm4/mupq/pqclean
KRAHMER_DIL_DIR := $(KRAHMER_PQCLEAN_ROOT)/crypto_sign/dilithium2/clean
KRAHMER_COMMON_DIR := $(KRAHMER_PQCLEAN_ROOT)/common
KRAHMER_TARGET_DIR := $(REPO_ROOT)/targets/krahmer_correction_fault
KRAHMER_BIN_DIR := $(BUILD_DIR)/bin/krahmer_correction_fault
KRAHMER_GENERATED_EVENT_HEADER := $(KRAHMER_DIL_DIR)/krahmer_microarch_events_generated.h

KRAHMER_PMU_TYPE ?= 4
KRAHMER_LOAD_CONFIG ?= 0x81d0
KRAHMER_STORE_CONFIG ?= 0x82d0

KRAHMER_DIL_SRCS := \
	$(KRAHMER_DIL_DIR)/ntt.c \
	$(KRAHMER_DIL_DIR)/packing.c \
	$(KRAHMER_DIL_DIR)/poly.c \
	$(KRAHMER_DIL_DIR)/polyvec.c \
	$(KRAHMER_DIL_DIR)/reduce.c \
	$(KRAHMER_DIL_DIR)/rounding.c \
	$(KRAHMER_DIL_DIR)/sign.c \
	$(KRAHMER_DIL_DIR)/symmetric-shake.c \
	$(KRAHMER_DIL_DIR)/krahmer_correction_fault_x86.c

KRAHMER_COMMON_SRCS := \
	$(KRAHMER_COMMON_DIR)/fips202.c \
	$(KRAHMER_COMMON_DIR)/randombytes.c

KRAHMER_ALL_SRCS := \
	$(KRAHMER_TARGET_DIR)/main.c \
	$(KRAHMER_DIL_SRCS) \
	$(KRAHMER_COMMON_SRCS)

KRAHMER_CPPFLAGS := \
	-D_GNU_SOURCE \
	-DPQCLEAN_DILITHIUM2_KRAHMER_X86=1 \
	-DKRAHMER_PMU_TYPE=$(KRAHMER_PMU_TYPE) \
	-DKRAHMER_LOAD_CONFIG=$(KRAHMER_LOAD_CONFIG) \
	-DKRAHMER_STORE_CONFIG=$(KRAHMER_STORE_CONFIG) \
	-I$(KRAHMER_DIL_DIR) \
	-I$(KRAHMER_COMMON_DIR)

KRAHMER_CFLAGS := \
	-O2 -g -std=c11 \
	-Wall -Wextra -Wpedantic \
	-fno-omit-frame-pointer \
	-fno-lto \
	-ffunction-sections \
	-fdata-sections

KRAHMER_LDFLAGS := -Wl,--gc-sections

KRAHMER_CORR_BASE_BIN := \
	$(KRAHMER_BIN_DIR)/correction_baseline
KRAHMER_CORR_ATTACK_BIN := \
	$(KRAHMER_BIN_DIR)/correction_skip
KRAHMER_A_BASE_BIN := \
	$(KRAHMER_BIN_DIR)/a_baseline
KRAHMER_A_ATTACK_BIN := \
	$(KRAHMER_BIN_DIR)/a_fault

KRAHMER_CORR_BASE_CACHE_BIN := \
	$(KRAHMER_BIN_DIR)/correction_baseline_cache
KRAHMER_CORR_ATTACK_CACHE_BIN := \
	$(KRAHMER_BIN_DIR)/correction_skip_cache
KRAHMER_A_BASE_CACHE_BIN := \
	$(KRAHMER_BIN_DIR)/a_baseline_cache
KRAHMER_A_ATTACK_CACHE_BIN := \
	$(KRAHMER_BIN_DIR)/a_fault_cache

KRAHMER_CORR_BASE_CACHE_DETAIL_BIN := \
	$(KRAHMER_BIN_DIR)/correction_baseline_cache_detail
KRAHMER_CORR_ATTACK_CACHE_DETAIL_BIN := \
	$(KRAHMER_BIN_DIR)/correction_skip_cache_detail
KRAHMER_A_BASE_CACHE_DETAIL_BIN := \
	$(KRAHMER_BIN_DIR)/a_baseline_cache_detail
KRAHMER_A_ATTACK_CACHE_DETAIL_BIN := \
	$(KRAHMER_BIN_DIR)/a_fault_cache_detail

KRAHMER_CORR_BASE_LOAD_HITS_BIN := \
	$(KRAHMER_BIN_DIR)/correction_baseline_load_hits
KRAHMER_CORR_ATTACK_LOAD_HITS_BIN := \
	$(KRAHMER_BIN_DIR)/correction_skip_load_hits
KRAHMER_A_BASE_LOAD_HITS_BIN := \
	$(KRAHMER_BIN_DIR)/a_baseline_load_hits
KRAHMER_A_ATTACK_LOAD_HITS_BIN := \
	$(KRAHMER_BIN_DIR)/a_fault_load_hits

KRAHMER_CORR_BASE_LOAD_MISSES_LATENCY_BIN := \
	$(KRAHMER_BIN_DIR)/correction_baseline_load_misses_latency
KRAHMER_CORR_ATTACK_LOAD_MISSES_LATENCY_BIN := \
	$(KRAHMER_BIN_DIR)/correction_skip_load_misses_latency
KRAHMER_A_BASE_LOAD_MISSES_LATENCY_BIN := \
	$(KRAHMER_BIN_DIR)/a_baseline_load_misses_latency
KRAHMER_A_ATTACK_LOAD_MISSES_LATENCY_BIN := \
	$(KRAHMER_BIN_DIR)/a_fault_load_misses_latency

KRAHMER_CORR_BASE_STALLS_BIN := \
	$(KRAHMER_BIN_DIR)/correction_baseline_stalls
KRAHMER_CORR_ATTACK_STALLS_BIN := \
	$(KRAHMER_BIN_DIR)/correction_skip_stalls
KRAHMER_A_BASE_STALLS_BIN := \
	$(KRAHMER_BIN_DIR)/a_baseline_stalls
KRAHMER_A_ATTACK_STALLS_BIN := \
	$(KRAHMER_BIN_DIR)/a_fault_stalls

KRAHMER_CORR_BASE_RECOVERY_BIN := \
	$(KRAHMER_BIN_DIR)/correction_baseline_recovery
KRAHMER_CORR_ATTACK_RECOVERY_BIN := \
	$(KRAHMER_BIN_DIR)/correction_skip_recovery
KRAHMER_A_BASE_RECOVERY_BIN := \
	$(KRAHMER_BIN_DIR)/a_baseline_recovery
KRAHMER_A_ATTACK_RECOVERY_BIN := \
	$(KRAHMER_BIN_DIR)/a_fault_recovery
.PHONY: krahmer-correction-fault krahmer-correction-fault-clean

krahmer-correction-fault: \
	$(KRAHMER_CORR_BASE_BIN) \
	$(KRAHMER_CORR_ATTACK_BIN) \
	$(KRAHMER_A_BASE_BIN) \
	$(KRAHMER_A_ATTACK_BIN) \
	$(KRAHMER_CORR_BASE_CACHE_BIN) \
	$(KRAHMER_CORR_ATTACK_CACHE_BIN) \
	$(KRAHMER_A_BASE_CACHE_BIN) \
	$(KRAHMER_A_ATTACK_CACHE_BIN) \
	$(KRAHMER_CORR_BASE_CACHE_DETAIL_BIN) \
	$(KRAHMER_CORR_ATTACK_CACHE_DETAIL_BIN) \
	$(KRAHMER_A_BASE_CACHE_DETAIL_BIN) \
	$(KRAHMER_A_ATTACK_CACHE_DETAIL_BIN) \
	$(KRAHMER_CORR_BASE_LOAD_HITS_BIN) \
	$(KRAHMER_CORR_ATTACK_LOAD_HITS_BIN) \
	$(KRAHMER_A_BASE_LOAD_HITS_BIN) \
	$(KRAHMER_A_ATTACK_LOAD_HITS_BIN) \
	$(KRAHMER_CORR_BASE_LOAD_MISSES_LATENCY_BIN) \
	$(KRAHMER_CORR_ATTACK_LOAD_MISSES_LATENCY_BIN) \
	$(KRAHMER_A_BASE_LOAD_MISSES_LATENCY_BIN) \
	$(KRAHMER_A_ATTACK_LOAD_MISSES_LATENCY_BIN) \
	$(KRAHMER_CORR_BASE_STALLS_BIN) \
	$(KRAHMER_CORR_ATTACK_STALLS_BIN) \
	$(KRAHMER_A_BASE_STALLS_BIN) \
	$(KRAHMER_A_ATTACK_STALLS_BIN) \
	$(KRAHMER_CORR_BASE_RECOVERY_BIN) \
	$(KRAHMER_CORR_ATTACK_RECOVERY_BIN) \
	$(KRAHMER_A_BASE_RECOVERY_BIN) \
	$(KRAHMER_A_ATTACK_RECOVERY_BIN)

$(KRAHMER_CORR_BASE_BIN): $(KRAHMER_ALL_SRCS) $(KRAHMER_GENERATED_EVENT_HEADER)
	mkdir -p $(dir $@)
	$(CC) $(KRAHMER_CPPFLAGS) $(KRAHMER_CFLAGS) \
		-DKRAHMER_VARIANT=1 -DKRAHMER_ATTACK_BUILD=0 -DKRAHMER_COUNTER_SET=0 \
		$(KRAHMER_ALL_SRCS) \
		$(KRAHMER_LDFLAGS) $(LDFLAGS) $(LDLIBS) -o $@

$(KRAHMER_CORR_ATTACK_BIN): $(KRAHMER_ALL_SRCS) $(KRAHMER_GENERATED_EVENT_HEADER)
	mkdir -p $(dir $@)
	$(CC) $(KRAHMER_CPPFLAGS) $(KRAHMER_CFLAGS) \
		-DKRAHMER_VARIANT=1 -DKRAHMER_ATTACK_BUILD=1 -DKRAHMER_COUNTER_SET=0 \
		$(KRAHMER_ALL_SRCS) \
		$(KRAHMER_LDFLAGS) $(LDFLAGS) $(LDLIBS) -o $@

$(KRAHMER_A_BASE_BIN): $(KRAHMER_ALL_SRCS) $(KRAHMER_GENERATED_EVENT_HEADER)
	mkdir -p $(dir $@)
	$(CC) $(KRAHMER_CPPFLAGS) $(KRAHMER_CFLAGS) \
		-DKRAHMER_VARIANT=2 -DKRAHMER_ATTACK_BUILD=0 -DKRAHMER_COUNTER_SET=0 \
		$(KRAHMER_ALL_SRCS) \
		$(KRAHMER_LDFLAGS) $(LDFLAGS) $(LDLIBS) -o $@

$(KRAHMER_A_ATTACK_BIN): $(KRAHMER_ALL_SRCS) $(KRAHMER_GENERATED_EVENT_HEADER)
	mkdir -p $(dir $@)
	$(CC) $(KRAHMER_CPPFLAGS) $(KRAHMER_CFLAGS) \
		-DKRAHMER_VARIANT=2 -DKRAHMER_ATTACK_BUILD=1 -DKRAHMER_COUNTER_SET=0 \
		$(KRAHMER_ALL_SRCS) \
		$(KRAHMER_LDFLAGS) $(LDFLAGS) $(LDLIBS) -o $@


$(KRAHMER_CORR_BASE_CACHE_BIN): $(KRAHMER_ALL_SRCS) $(KRAHMER_GENERATED_EVENT_HEADER)
	mkdir -p $(dir $@)
	$(CC) $(KRAHMER_CPPFLAGS) $(KRAHMER_CFLAGS) \
		-DKRAHMER_VARIANT=1 -DKRAHMER_ATTACK_BUILD=0 -DKRAHMER_COUNTER_SET=1 \
		$(KRAHMER_ALL_SRCS) \
		$(KRAHMER_LDFLAGS) $(LDFLAGS) $(LDLIBS) -o $@

$(KRAHMER_CORR_ATTACK_CACHE_BIN): $(KRAHMER_ALL_SRCS) $(KRAHMER_GENERATED_EVENT_HEADER)
	mkdir -p $(dir $@)
	$(CC) $(KRAHMER_CPPFLAGS) $(KRAHMER_CFLAGS) \
		-DKRAHMER_VARIANT=1 -DKRAHMER_ATTACK_BUILD=1 -DKRAHMER_COUNTER_SET=1 \
		$(KRAHMER_ALL_SRCS) \
		$(KRAHMER_LDFLAGS) $(LDFLAGS) $(LDLIBS) -o $@

$(KRAHMER_A_BASE_CACHE_BIN): $(KRAHMER_ALL_SRCS) $(KRAHMER_GENERATED_EVENT_HEADER)
	mkdir -p $(dir $@)
	$(CC) $(KRAHMER_CPPFLAGS) $(KRAHMER_CFLAGS) \
		-DKRAHMER_VARIANT=2 -DKRAHMER_ATTACK_BUILD=0 -DKRAHMER_COUNTER_SET=1 \
		$(KRAHMER_ALL_SRCS) \
		$(KRAHMER_LDFLAGS) $(LDFLAGS) $(LDLIBS) -o $@

$(KRAHMER_A_ATTACK_CACHE_BIN): $(KRAHMER_ALL_SRCS) $(KRAHMER_GENERATED_EVENT_HEADER)
	mkdir -p $(dir $@)
	$(CC) $(KRAHMER_CPPFLAGS) $(KRAHMER_CFLAGS) \
		-DKRAHMER_VARIANT=2 -DKRAHMER_ATTACK_BUILD=1 -DKRAHMER_COUNTER_SET=1 \
		$(KRAHMER_ALL_SRCS) \
		$(KRAHMER_LDFLAGS) $(LDFLAGS) $(LDLIBS) -o $@

$(KRAHMER_CORR_BASE_CACHE_DETAIL_BIN): $(KRAHMER_ALL_SRCS) $(KRAHMER_GENERATED_EVENT_HEADER)
	mkdir -p $(dir $@)
	$(CC) $(KRAHMER_CPPFLAGS) $(KRAHMER_CFLAGS) \
		-DKRAHMER_VARIANT=1 -DKRAHMER_ATTACK_BUILD=0 -DKRAHMER_COUNTER_SET=2 \
		$(KRAHMER_ALL_SRCS) \
		$(KRAHMER_LDFLAGS) $(LDFLAGS) $(LDLIBS) -o $@

$(KRAHMER_CORR_ATTACK_CACHE_DETAIL_BIN): $(KRAHMER_ALL_SRCS) $(KRAHMER_GENERATED_EVENT_HEADER)
	mkdir -p $(dir $@)
	$(CC) $(KRAHMER_CPPFLAGS) $(KRAHMER_CFLAGS) \
		-DKRAHMER_VARIANT=1 -DKRAHMER_ATTACK_BUILD=1 -DKRAHMER_COUNTER_SET=2 \
		$(KRAHMER_ALL_SRCS) \
		$(KRAHMER_LDFLAGS) $(LDFLAGS) $(LDLIBS) -o $@

$(KRAHMER_A_BASE_CACHE_DETAIL_BIN): $(KRAHMER_ALL_SRCS) $(KRAHMER_GENERATED_EVENT_HEADER)
	mkdir -p $(dir $@)
	$(CC) $(KRAHMER_CPPFLAGS) $(KRAHMER_CFLAGS) \
		-DKRAHMER_VARIANT=2 -DKRAHMER_ATTACK_BUILD=0 -DKRAHMER_COUNTER_SET=2 \
		$(KRAHMER_ALL_SRCS) \
		$(KRAHMER_LDFLAGS) $(LDFLAGS) $(LDLIBS) -o $@

$(KRAHMER_A_ATTACK_CACHE_DETAIL_BIN): $(KRAHMER_ALL_SRCS) $(KRAHMER_GENERATED_EVENT_HEADER)
	mkdir -p $(dir $@)
	$(CC) $(KRAHMER_CPPFLAGS) $(KRAHMER_CFLAGS) \
		-DKRAHMER_VARIANT=2 -DKRAHMER_ATTACK_BUILD=1 -DKRAHMER_COUNTER_SET=2 \
		$(KRAHMER_ALL_SRCS) \
		$(KRAHMER_LDFLAGS) $(LDFLAGS) $(LDLIBS) -o $@

$(KRAHMER_CORR_BASE_LOAD_HITS_BIN): $(KRAHMER_ALL_SRCS) $(KRAHMER_GENERATED_EVENT_HEADER)
	mkdir -p $(dir $@)
	$(CC) $(KRAHMER_CPPFLAGS) $(KRAHMER_CFLAGS) \
		-DKRAHMER_VARIANT=1 -DKRAHMER_ATTACK_BUILD=0 -DKRAHMER_COUNTER_SET=3 \
		$(KRAHMER_ALL_SRCS) \
		$(KRAHMER_LDFLAGS) $(LDFLAGS) $(LDLIBS) -o $@

$(KRAHMER_CORR_ATTACK_LOAD_HITS_BIN): $(KRAHMER_ALL_SRCS) $(KRAHMER_GENERATED_EVENT_HEADER)
	mkdir -p $(dir $@)
	$(CC) $(KRAHMER_CPPFLAGS) $(KRAHMER_CFLAGS) \
		-DKRAHMER_VARIANT=1 -DKRAHMER_ATTACK_BUILD=1 -DKRAHMER_COUNTER_SET=3 \
		$(KRAHMER_ALL_SRCS) \
		$(KRAHMER_LDFLAGS) $(LDFLAGS) $(LDLIBS) -o $@

$(KRAHMER_A_BASE_LOAD_HITS_BIN): $(KRAHMER_ALL_SRCS) $(KRAHMER_GENERATED_EVENT_HEADER)
	mkdir -p $(dir $@)
	$(CC) $(KRAHMER_CPPFLAGS) $(KRAHMER_CFLAGS) \
		-DKRAHMER_VARIANT=2 -DKRAHMER_ATTACK_BUILD=0 -DKRAHMER_COUNTER_SET=3 \
		$(KRAHMER_ALL_SRCS) \
		$(KRAHMER_LDFLAGS) $(LDFLAGS) $(LDLIBS) -o $@

$(KRAHMER_A_ATTACK_LOAD_HITS_BIN): $(KRAHMER_ALL_SRCS) $(KRAHMER_GENERATED_EVENT_HEADER)
	mkdir -p $(dir $@)
	$(CC) $(KRAHMER_CPPFLAGS) $(KRAHMER_CFLAGS) \
		-DKRAHMER_VARIANT=2 -DKRAHMER_ATTACK_BUILD=1 -DKRAHMER_COUNTER_SET=3 \
		$(KRAHMER_ALL_SRCS) \
		$(KRAHMER_LDFLAGS) $(LDFLAGS) $(LDLIBS) -o $@

$(KRAHMER_CORR_BASE_LOAD_MISSES_LATENCY_BIN): $(KRAHMER_ALL_SRCS) $(KRAHMER_GENERATED_EVENT_HEADER)
	mkdir -p $(dir $@)
	$(CC) $(KRAHMER_CPPFLAGS) $(KRAHMER_CFLAGS) \
		-DKRAHMER_VARIANT=1 -DKRAHMER_ATTACK_BUILD=0 -DKRAHMER_COUNTER_SET=4 \
		$(KRAHMER_ALL_SRCS) \
		$(KRAHMER_LDFLAGS) $(LDFLAGS) $(LDLIBS) -o $@

$(KRAHMER_CORR_ATTACK_LOAD_MISSES_LATENCY_BIN): $(KRAHMER_ALL_SRCS) $(KRAHMER_GENERATED_EVENT_HEADER)
	mkdir -p $(dir $@)
	$(CC) $(KRAHMER_CPPFLAGS) $(KRAHMER_CFLAGS) \
		-DKRAHMER_VARIANT=1 -DKRAHMER_ATTACK_BUILD=1 -DKRAHMER_COUNTER_SET=4 \
		$(KRAHMER_ALL_SRCS) \
		$(KRAHMER_LDFLAGS) $(LDFLAGS) $(LDLIBS) -o $@

$(KRAHMER_A_BASE_LOAD_MISSES_LATENCY_BIN): $(KRAHMER_ALL_SRCS) $(KRAHMER_GENERATED_EVENT_HEADER)
	mkdir -p $(dir $@)
	$(CC) $(KRAHMER_CPPFLAGS) $(KRAHMER_CFLAGS) \
		-DKRAHMER_VARIANT=2 -DKRAHMER_ATTACK_BUILD=0 -DKRAHMER_COUNTER_SET=4 \
		$(KRAHMER_ALL_SRCS) \
		$(KRAHMER_LDFLAGS) $(LDFLAGS) $(LDLIBS) -o $@

$(KRAHMER_A_ATTACK_LOAD_MISSES_LATENCY_BIN): $(KRAHMER_ALL_SRCS) $(KRAHMER_GENERATED_EVENT_HEADER)
	mkdir -p $(dir $@)
	$(CC) $(KRAHMER_CPPFLAGS) $(KRAHMER_CFLAGS) \
		-DKRAHMER_VARIANT=2 -DKRAHMER_ATTACK_BUILD=1 -DKRAHMER_COUNTER_SET=4 \
		$(KRAHMER_ALL_SRCS) \
		$(KRAHMER_LDFLAGS) $(LDFLAGS) $(LDLIBS) -o $@

$(KRAHMER_CORR_BASE_STALLS_BIN): $(KRAHMER_ALL_SRCS) $(KRAHMER_GENERATED_EVENT_HEADER)
	mkdir -p $(dir $@)
	$(CC) $(KRAHMER_CPPFLAGS) $(KRAHMER_CFLAGS) \
		-DKRAHMER_VARIANT=1 -DKRAHMER_ATTACK_BUILD=0 -DKRAHMER_COUNTER_SET=5 \
		$(KRAHMER_ALL_SRCS) \
		$(KRAHMER_LDFLAGS) $(LDFLAGS) $(LDLIBS) -o $@

$(KRAHMER_CORR_ATTACK_STALLS_BIN): $(KRAHMER_ALL_SRCS) $(KRAHMER_GENERATED_EVENT_HEADER)
	mkdir -p $(dir $@)
	$(CC) $(KRAHMER_CPPFLAGS) $(KRAHMER_CFLAGS) \
		-DKRAHMER_VARIANT=1 -DKRAHMER_ATTACK_BUILD=1 -DKRAHMER_COUNTER_SET=5 \
		$(KRAHMER_ALL_SRCS) \
		$(KRAHMER_LDFLAGS) $(LDFLAGS) $(LDLIBS) -o $@

$(KRAHMER_A_BASE_STALLS_BIN): $(KRAHMER_ALL_SRCS) $(KRAHMER_GENERATED_EVENT_HEADER)
	mkdir -p $(dir $@)
	$(CC) $(KRAHMER_CPPFLAGS) $(KRAHMER_CFLAGS) \
		-DKRAHMER_VARIANT=2 -DKRAHMER_ATTACK_BUILD=0 -DKRAHMER_COUNTER_SET=5 \
		$(KRAHMER_ALL_SRCS) \
		$(KRAHMER_LDFLAGS) $(LDFLAGS) $(LDLIBS) -o $@

$(KRAHMER_A_ATTACK_STALLS_BIN): $(KRAHMER_ALL_SRCS) $(KRAHMER_GENERATED_EVENT_HEADER)
	mkdir -p $(dir $@)
	$(CC) $(KRAHMER_CPPFLAGS) $(KRAHMER_CFLAGS) \
		-DKRAHMER_VARIANT=2 -DKRAHMER_ATTACK_BUILD=1 -DKRAHMER_COUNTER_SET=5 \
		$(KRAHMER_ALL_SRCS) \
		$(KRAHMER_LDFLAGS) $(LDFLAGS) $(LDLIBS) -o $@

$(KRAHMER_CORR_BASE_RECOVERY_BIN): $(KRAHMER_ALL_SRCS) $(KRAHMER_GENERATED_EVENT_HEADER)
	mkdir -p $(dir $@)
	$(CC) $(KRAHMER_CPPFLAGS) $(KRAHMER_CFLAGS) \
		-DKRAHMER_VARIANT=1 -DKRAHMER_ATTACK_BUILD=0 -DKRAHMER_COUNTER_SET=6 \
		$(KRAHMER_ALL_SRCS) \
		$(KRAHMER_LDFLAGS) $(LDFLAGS) $(LDLIBS) -o $@

$(KRAHMER_CORR_ATTACK_RECOVERY_BIN): $(KRAHMER_ALL_SRCS) $(KRAHMER_GENERATED_EVENT_HEADER)
	mkdir -p $(dir $@)
	$(CC) $(KRAHMER_CPPFLAGS) $(KRAHMER_CFLAGS) \
		-DKRAHMER_VARIANT=1 -DKRAHMER_ATTACK_BUILD=1 -DKRAHMER_COUNTER_SET=6 \
		$(KRAHMER_ALL_SRCS) \
		$(KRAHMER_LDFLAGS) $(LDFLAGS) $(LDLIBS) -o $@

$(KRAHMER_A_BASE_RECOVERY_BIN): $(KRAHMER_ALL_SRCS) $(KRAHMER_GENERATED_EVENT_HEADER)
	mkdir -p $(dir $@)
	$(CC) $(KRAHMER_CPPFLAGS) $(KRAHMER_CFLAGS) \
		-DKRAHMER_VARIANT=2 -DKRAHMER_ATTACK_BUILD=0 -DKRAHMER_COUNTER_SET=6 \
		$(KRAHMER_ALL_SRCS) \
		$(KRAHMER_LDFLAGS) $(LDFLAGS) $(LDLIBS) -o $@

$(KRAHMER_A_ATTACK_RECOVERY_BIN): $(KRAHMER_ALL_SRCS) $(KRAHMER_GENERATED_EVENT_HEADER)
	mkdir -p $(dir $@)
	$(CC) $(KRAHMER_CPPFLAGS) $(KRAHMER_CFLAGS) \
		-DKRAHMER_VARIANT=2 -DKRAHMER_ATTACK_BUILD=1 -DKRAHMER_COUNTER_SET=6 \
		$(KRAHMER_ALL_SRCS) \
		$(KRAHMER_LDFLAGS) $(LDFLAGS) $(LDLIBS) -o $@
krahmer-correction-fault-clean:
	rm -rf $(KRAHMER_BIN_DIR)
